name: main
concurrency: main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      cliVersion:
        description: 'CLI version'
        required: false
        default: ''

permissions:
  contents: read
  packages: write

jobs:
  build-container:
    runs-on: ubuntu-latest
    outputs:
      timestamp1: ${{ steps.build1.outputs.timestamp1 }}
      timestamp2: ${{ steps.build2.outputs.timestamp2 }}

    steps:
    - uses: actions/checkout@v4
      name: checkout code

    - name: Set CLI version
      if: ${{ inputs.cliVersion != '' }}
      run: |
        # https://github.com/devcontainers/ci/issues/252
        npm install --global @devcontainers/cli@${{ inputs.cliVersion }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      if: github.ref == 'refs/heads/main'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build dev container
      uses: devcontainers/ci@v0.3
      id: build1
      with:
        imageName: "ghcr.io/stuartleeks/fuzzy-couscous/dev-container"
        cacheFrom: "ghcr.io/stuartleeks/fuzzy-couscous/dev-container"
        refFilterForPush: refs/heads/main
        env: |
          GITHUB_STEP_SUMMARY
          GITHUB_OUTPUT
        runCmd: |
          set -e

          echo -e "=\n=\n"
          echo "= Timestamp1: $(cat /usr/local/etc/dc-timestamp.txt)"
          echo -e "=\n=\n"

          echo "Timestamp1: $(cat /usr/local/etc/dc-timestamp.txt)" >> $GITHUB_STEP_SUMMARY
          echo "timestamp1=$(cat /usr/local/etc/dc-timestamp.txt)" >> $GITHUB_OUTPUT

    - name: Build dev container (2)
      id: build2
      uses: devcontainers/ci@v0.3
      with:
        imageName: "ghcr.io/stuartleeks/fuzzy-couscous/dev-container"
        cacheFrom: "ghcr.io/stuartleeks/fuzzy-couscous/dev-container"
        refFilterForPush: refs/heads/main
        env: |
          GITHUB_STEP_SUMMARY
          GITHUB_OUTPUT
        runCmd: |
          set -e

          echo -e "=\n=\n"
          echo "= Timestamp2: $(cat /usr/local/etc/dc-timestamp.txt)"
          echo -e "=\n=\n"

          echo "Timestamp2: $(cat /usr/local/etc/dc-timestamp.txt)" >> $GITHUB_STEP_SUMMARY
          echo "timestamp2=$(cat /usr/local/etc/dc-timestamp.txt)" >> $GITHUB_OUTPUT

          echo "===== GH OUTPUT START ====="
          cat "$GITHUB_OUTPUT"
          echo "===== GH OUTPUT END ====="

  build-container-repeat:
    runs-on: ubuntu-latest
    needs: build-container

    steps:
    - uses: actions/checkout@v4
      name: checkout code

    - name: Set CLI version
      if: ${{ inputs.cliVersion != '' }}
      run: |
        # https://github.com/devcontainers/ci/issues/252
        npm install --global @devcontainers/cli@${{ inputs.cliVersion }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      if: github.ref == 'refs/heads/main'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build dev container
      id: build3
      uses: devcontainers/ci@v0.3
      with:
        imageName: "ghcr.io/stuartleeks/fuzzy-couscous/dev-container"
        cacheFrom: "ghcr.io/stuartleeks/fuzzy-couscous/dev-container"
        refFilterForPush: refs/heads/main
        env: |
          GITHUB_STEP_SUMMARY
          GITHUB_OUTPUT
        runCmd: |
          set -e

          echo -e "=\n=\n"
          echo "= Timestamp3: $(cat /usr/local/etc/dc-timestamp.txt)"
          echo -e "=\n=\n"

          echo "Timestamp3: $(cat /usr/local/etc/dc-timestamp.txt)" >> $GITHUB_STEP_SUMMARY

          echo "timestamp3=$(cat /usr/local/etc/dc-timestamp.txt)" >> $GITHUB_OUTPUT


    - name: check values
      id: check
      env:
        TIMESTAMP1: ${{ needs.build-container.outputs.timestamp1 }}
        TIMESTAMP2: ${{ needs.build-container.outputs.timestamp2 }}
        TIMESTAMP3: ${{ steps.build3.outputs.timestamp3 }}
      run: |
        echo "TIMESTAMP1: $TIMESTAMP1"
        echo "TIMESTAMP2: $TIMESTAMP2"
        echo "TIMESTAMP3: $TIMESTAMP3"

        if [ "$TIMESTAMP1" != "$TIMESTAMP2" ]; then
          echo "Timestamp1 and Timestamp2 are different"
          exit 1
        fi

        if [ "$TIMESTAMP1" != "$TIMESTAMP3" ]; then
          echo "Timestamp1 and Timestamp3 are different"
          exit 1
        fi

        if [ "$TIMESTAMP2" != "$TIMESTAMP3" ]; then
          echo "Timestamp2 and Timestamp3 are different"
          exit 1
        fi

        echo "All timestamps are the same"
